### ISSUE TITLE
Issue with "add a childnode"

### ISSUE THREAD

**Issue by tadassce** [AndrewRadev/andrews_nerdtree.vim#2]
Hey Andrew!

I've noticed that adding a childnode doesn't seem to be working. I can reproduce this every time: I open NERDTree, hit `ma` wanting to add a new child node, then I see this:

```
NERDTree Menu. Use j/k/enter, or the shortcuts indicated
=========================================================
> (a)dd a childnode
  (m)ove the current node
  (d)elete the curent node
  (c)opy the current node
  (e)dit directory contents
  e(x)ecute

Error detected while processing function nerdtree#ui_glue#invokeKeyMap[1]..76[33]..75[3]..<SNR>73_showMenu[2]..49[29]..66[9]..andrews_nerdtree#buffer_fs_menu#AddNode:
line    2:
E716: Key not present in Dictionary: Slash()
line    4:
E121: Undefined variable: path
E116: Invalid arguments for function andrews_nerdtree#buffer_fs_menu#InputBufferSetup
Press ENTER or type command to continue
```

I have `let g:andrews_nerdtree_all = 1` set, and disabling it "solves" the problem.

Am I doing something wrong? Can I help debug this better?

**Comment by AndrewRadev** [comment]
I think it's likely I haven't updated my NERDTree in a long time and it's changed its API. I'll check it out.

To be clear on which version I'm looking at, could you let me know the SHA you're currently on? Also the remote, because I think the repo has been moved :D

**Comment by tadassce** [comment]
Oh sure, I'm on `master` on both:
- `AndrewRadev/andrews_nerdtree.vim` (this repo/remote) - 5817e9b and
- scrooloose/nerdtree@577ddc7

**Comment by AndrewRadev** [comment]
Alright, I pulled NERDTree master and applied a fix -- seems to work for me now. Could you check it out?

**Comment by tadassce** [comment]
like a charm! thank you 🙇
